# This file was generated by liblab | https://liblab.com/

from typing import Union
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({"date_": "date"})
class AssignmentDataOUt(BaseModel):
    """AssignmentDataOUt

    :param _id: _id, defaults to None
    :type _id: str, optional
    :param title: title
    :type title: str
    :param date_: date_
    :type date_: str
    """

    def __init__(
        self, title: str, date_: str, _id: Union[str, None] = SENTINEL, **kwargs
    ):
        """AssignmentDataOUt

        :param _id: _id, defaults to None
        :type _id: str, optional
        :param title: title
        :type title: str
        :param date_: date_
        :type date_: str
        """
        if _id is not SENTINEL:
            self._id = self._define_str("_id", _id, nullable=True)
        self.title = title
        self.date_ = date_
        self._kwargs = kwargs
