# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"id_": "id"})
class CoursesSchemaOut(BaseModel):
    """CoursesSchemaOut

    :param id_: id_
    :type id_: str
    :param title: title
    :type title: str
    """

    def __init__(self, id_: str, title: str, **kwargs):
        """CoursesSchemaOut

        :param id_: id_
        :type id_: str
        :param title: title
        :type title: str
        """
        self.id_ = id_
        self.title = title
        self._kwargs = kwargs
