# This file was generated by liblab | https://liblab.com/

from typing import List
from typing import Union
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({})
class Course(BaseModel):
    """Course

    :param _id: _id, defaults to None
    :type _id: str, optional
    :param title: title
    :type title: str
    :param description: description, defaults to None
    :type description: str, optional
    :param materials: materials, defaults to None
    :type materials: List[str], optional
    :param teacher_id: teacher_id
    :type teacher_id: str
    :param assignments: assignments
    :type assignments: List[str]
    :param lessons: lessons
    :type lessons: List[str]
    :param students: students
    :type students: List[str]
    """

    def __init__(
        self,
        title: str,
        teacher_id: Union[str, None],
        assignments: Union[List[str], None],
        lessons: Union[List[str], None],
        students: Union[List[str], None],
        _id: Union[str, None] = SENTINEL,
        description: Union[str, None] = SENTINEL,
        materials: Union[List[str], None] = SENTINEL,
        **kwargs
    ):
        """Course

        :param _id: _id, defaults to None
        :type _id: str, optional
        :param title: title
        :type title: str
        :param description: description, defaults to None
        :type description: str, optional
        :param materials: materials, defaults to None
        :type materials: List[str], optional
        :param teacher_id: teacher_id
        :type teacher_id: str
        :param assignments: assignments
        :type assignments: List[str]
        :param lessons: lessons
        :type lessons: List[str]
        :param students: students
        :type students: List[str]
        """
        if _id is not SENTINEL:
            self._id = self._define_str("_id", _id, nullable=True)
        self.title = title
        if description is not SENTINEL:
            self.description = self._define_str(
                "description", description, nullable=True
            )
        if materials is not SENTINEL:
            self.materials = materials
        self.teacher_id = self._define_str("teacher_id", teacher_id, nullable=True)
        self.assignments = assignments
        self.lessons = lessons
        self.students = students
        self._kwargs = kwargs
