# This file was generated by liblab | https://liblab.com/

from typing import List
from typing import Union
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({"date_": "date"})
class Lesson(BaseModel):
    """Lesson

    :param _id: _id, defaults to None
    :type _id: str, optional
    :param course_id: course_id
    :type course_id: str
    :param title: title, defaults to None
    :type title: str, optional
    :param date_: date_
    :type date_: str
    :param description: description
    :type description: str
    :param materials: materials
    :type materials: List[str]
    :param location: location
    :type location: str
    :param duration: duration
    :type duration: str
    """

    def __init__(
        self,
        course_id: str,
        date_: Union[str, None],
        description: Union[str, None],
        materials: Union[List[str], None],
        location: str,
        duration: str,
        _id: Union[str, None] = SENTINEL,
        title: str = SENTINEL,
        **kwargs
    ):
        """Lesson

        :param _id: _id, defaults to None
        :type _id: str, optional
        :param course_id: course_id
        :type course_id: str
        :param title: title, defaults to None
        :type title: str, optional
        :param date_: date_
        :type date_: str
        :param description: description
        :type description: str
        :param materials: materials
        :type materials: List[str]
        :param location: location
        :type location: str
        :param duration: duration
        :type duration: str
        """
        if _id is not SENTINEL:
            self._id = self._define_str("_id", _id, nullable=True)
        self.course_id = course_id
        if title is not SENTINEL:
            self.title = title
        self.date_ = self._define_str("date_", date_, nullable=True)
        self.description = self._define_str("description", description, nullable=True)
        self.materials = materials
        self.location = location
        self.duration = duration
        self._kwargs = kwargs
