# This file was generated by liblab | https://liblab.com/

from enum import Enum


class Order(Enum):
    """An enumeration representing different categories.

    :cvar ASK: "ask"
    :vartype ASK: str
    :cvar DESC: "desc"
    :vartype DESC: str
    """

    ASK = "ask"
    DESC = "desc"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, Order._member_map_.values()))
