# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({})
class ShortCourseDataOut(BaseModel):
    """ShortCourseDataOut

    :param _id: _id, defaults to None
    :type _id: str, optional
    :param title: title
    :type title: str
    """

    def __init__(self, title: str, _id: str = SENTINEL, **kwargs):
        """ShortCourseDataOut

        :param _id: _id, defaults to None
        :type _id: str, optional
        :param title: title
        :type title: str
        """
        if _id is not SENTINEL:
            self._id = _id
        self.title = title
        self._kwargs = kwargs
