# This file was generated by liblab | https://liblab.com/

from enum import Enum


class Status(Enum):
    """An enumeration representing different categories.

    :cvar READY: "ready"
    :vartype READY: str
    :cvar NOTREADY: "not ready"
    :vartype NOTREADY: str
    :cvar ASSESSED: "assessed"
    :vartype ASSESSED: str
    """

    READY = "ready"
    NOTREADY = "not ready"
    ASSESSED = "assessed"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, Status._member_map_.values()))
