# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({})
class StudentShortSchemaOut(BaseModel):
    """StudentShortSchemaOut

    :param _id: _id, defaults to None
    :type _id: str, optional
    :param tg_id: tg_id
    :type tg_id: str
    :param name: name
    :type name: str
    """

    def __init__(self, tg_id: str, name: str, _id: str = SENTINEL, **kwargs):
        """StudentShortSchemaOut

        :param _id: _id, defaults to None
        :type _id: str, optional
        :param tg_id: tg_id
        :type tg_id: str
        :param name: name
        :type name: str
        """
        if _id is not SENTINEL:
            self._id = _id
        self.tg_id = tg_id
        self.name = name
        self._kwargs = kwargs
