# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from typing import Union
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .student_assignment_schema_out import StudentAssignmentSchemaOut


@JsonMap({})
class StudentAssignmentSchemaOutList(BaseModel):
    """StudentAssignmentSchemaOutList

    :param assignments: assignments
    :type assignments: List[StudentAssignmentSchemaOut]
    """

    def __init__(
        self, assignments: Union[List[StudentAssignmentSchemaOut], None], **kwargs
    ):
        """StudentAssignmentSchemaOutList

        :param assignments: assignments
        :type assignments: List[StudentAssignmentSchemaOut]
        """
        self.assignments = self._define_list(assignments, StudentAssignmentSchemaOut)
        self._kwargs = kwargs
