# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .short_course_data_out import ShortCourseDataOut


@JsonMap({})
class StudentCoursesList(BaseModel):
    """StudentCoursesList

    :param courses: courses
    :type courses: List[ShortCourseDataOut]
    """

    def __init__(self, courses: List[ShortCourseDataOut], **kwargs):
        """StudentCoursesList

        :param courses: courses
        :type courses: List[ShortCourseDataOut]
        """
        self.courses = self._define_list(courses, ShortCourseDataOut)
        self._kwargs = kwargs
