# This file was generated by liblab | https://liblab.com/

from typing import List
from typing import Union
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({"date_": "date"})
class StudentAssignmentSchemaOut(BaseModel):
    """StudentAssignmentSchemaOut

    :param _id: _id, defaults to None
    :type _id: str, optional
    :param course_id: course_id
    :type course_id: str
    :param title: title, defaults to None
    :type title: str, optional
    :param date_: date_
    :type date_: str
    :param description: description
    :type description: str
    :param materials: materials
    :type materials: List[str]
    :param max_score: max_score, defaults to None
    :type max_score: int, optional
    :param assignment_id: assignment_id
    :type assignment_id: str
    :param status: status, defaults to None
    :type status: str, optional
    :param mark: mark, defaults to None
    :type mark: int, optional
    :param course_title: course_title
    :type course_title: str
    """

    def __init__(
        self,
        course_id: str,
        date_: Union[str, None],
        description: Union[str, None],
        materials: Union[List[str], None],
        assignment_id: str,
        course_title: Union[str, None],
        _id: Union[str, None] = SENTINEL,
        title: str = SENTINEL,
        max_score: int = SENTINEL,
        status: str = SENTINEL,
        mark: int = SENTINEL,
        **kwargs
    ):
        """StudentAssignmentSchemaOut

        :param _id: _id, defaults to None
        :type _id: str, optional
        :param course_id: course_id
        :type course_id: str
        :param title: title, defaults to None
        :type title: str, optional
        :param date_: date_
        :type date_: str
        :param description: description
        :type description: str
        :param materials: materials
        :type materials: List[str]
        :param max_score: max_score, defaults to None
        :type max_score: int, optional
        :param assignment_id: assignment_id
        :type assignment_id: str
        :param status: status, defaults to None
        :type status: str, optional
        :param mark: mark, defaults to None
        :type mark: int, optional
        :param course_title: course_title
        :type course_title: str
        """
        if _id is not SENTINEL:
            self._id = self._define_str("_id", _id, nullable=True)
        self.course_id = course_id
        if title is not SENTINEL:
            self.title = title
        self.date_ = self._define_str("date_", date_, nullable=True)
        self.description = self._define_str("description", description, nullable=True)
        self.materials = materials
        if max_score is not SENTINEL:
            self.max_score = max_score
        self.assignment_id = assignment_id
        if status is not SENTINEL:
            self.status = status
        if mark is not SENTINEL:
            self.mark = mark
        self.course_title = self._define_str(
            "course_title", course_title, nullable=True
        )
        self._kwargs = kwargs
