# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .student_lessons_short_schema_out import StudentLessonsShortSchemaOut


@JsonMap({"date_": "date"})
class StudentWeekdayLessonsSchemaOut(BaseModel):
    """StudentWeekdayLessonsSchemaOut

    :param weekday: weekday
    :type weekday: str
    :param date_: date_
    :type date_: str
    :param lessons: lessons
    :type lessons: List[StudentLessonsShortSchemaOut]
    """

    def __init__(
        self,
        weekday: str,
        date_: str,
        lessons: List[StudentLessonsShortSchemaOut],
        **kwargs,
    ):
        """StudentWeekdayLessonsSchemaOut

        :param weekday: weekday
        :type weekday: str
        :param date_: date_
        :type date_: str
        :param lessons: lessons
        :type lessons: List[StudentLessonsShortSchemaOut]
        """
        self.weekday = weekday
        self.date_ = date_
        self.lessons = self._define_list(lessons, StudentLessonsShortSchemaOut)
        self._kwargs = kwargs
