# This file was generated by liblab | https://liblab.com/

from typing import Awaitable, List
from .utils.to_async import to_async
from ..assignments import AssignmentsService
from ...models import Assignment


class AssignmentsServiceAsync(AssignmentsService):
    """
    Async Wrapper for AssignmentsServiceAsync
    """

    def add_assignment_assignments_new_post(
        self, request_body: Assignment
    ) -> Awaitable[any]:
        return to_async(super().add_assignment_assignments_new_post)(request_body)

    def add_assignments_assignments_new_many_post(
        self, request_body: List[Assignment]
    ) -> Awaitable[any]:
        return to_async(super().add_assignments_assignments_new_many_post)(request_body)

    def get_by_id_assignments_id_get(self, id_: str) -> Awaitable[Assignment]:
        return to_async(super().get_by_id_assignments_id_get)(id_)
