# This file was generated by liblab | https://liblab.com/

from typing import Awaitable
from .utils.to_async import to_async
from ..auth import AuthService


class AuthServiceAsync(AuthService):
    """
    Async Wrapper for AuthServiceAsync
    """

    def get_user_status_auth_check_user_tg_id_get(self, tg_id: str) -> Awaitable[any]:
        return to_async(super().get_user_status_auth_check_user_tg_id_get)(tg_id)
