# This file was generated by liblab | https://liblab.com/

from typing import Awaitable
from .utils.to_async import to_async
from ..index import IndexService


class IndexServiceAsync(IndexService):
    """
    Async Wrapper for IndexServiceAsync
    """

    def root_get(self) -> Awaitable[any]:
        return to_async(super().root_get)()
