# This file was generated by liblab | https://liblab.com/

from typing import Awaitable, List
from .utils.to_async import to_async
from ..lessons import LessonsService
from ...models import Lesson


class LessonsServiceAsync(LessonsService):
    """
    Async Wrapper for LessonsServiceAsync
    """

    def add_lesson_lessons_new_post(self, request_body: Lesson) -> Awaitable[any]:
        return to_async(super().add_lesson_lessons_new_post)(request_body)

    def add_lessons_lessons_new_many_post(
        self, request_body: List[Lesson]
    ) -> Awaitable[any]:
        return to_async(super().add_lessons_lessons_new_many_post)(request_body)

    def get_by_id_lessons_id_get(self, id_: str) -> Awaitable[Lesson]:
        return to_async(super().get_by_id_lessons_id_get)(id_)
