# This file was generated by liblab | https://liblab.com/

from typing import Awaitable
from .utils.to_async import to_async
from ..sentry_debug import SentryDebugService


class SentryDebugServiceAsync(SentryDebugService):
    """
    Async Wrapper for SentryDebugServiceAsync
    """

    def trigger_error_sentry_debug_get(self) -> Awaitable[any]:
        return to_async(super().trigger_error_sentry_debug_get)()
